name: Go Test Linux
on:
  push: null
permissions:
  contents: read
jobs:
  get-go-version:
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.get-go-version.outputs.go-version }}
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
    - name: Determine Go version
      id: get-go-version
      run: 'echo "Found Go $(cat .go-version)"

        echo "go-version=$(cat .go-version)" >> $GITHUB_OUTPUT

        '
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
    - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491
      with:
        go-version: ${{ steps.get-go-version.outputs.go-version }}
    - run: 'echo "Testing with Go ${{ steps.get-go-version.outputs.go-version }}"

        go test -race -count 1 ./... -timeout=3m

        '
