name: Go Validate
on:
  push: null
permissions:
  contents: read
jobs:
  get-go-version:
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.get-go-version.outputs.go-version }}
    steps:
    - name: stepify-probe-get-go-version
      run: echo stepify-probe-get-go-version
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
    - name: Determine Go version
      id: get-go-version
      run: 'echo "Found Go $(cat .go-version)"

        echo "go-version=$(cat .go-version)" >> $GITHUB_OUTPUT

        '
    - name: stepify-tail-get-go-version
      run: echo stepify-tail-get-go-version
    - name: stepify-probe-check-mod-tidy
      run: echo stepify-probe-check-mod-tidy
    - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491
      with:
        go-version: ${{ steps.get-go-version.outputs.go-version }}
    - run: go mod tidy
    - name: stepify-tail-check-mod-tidy
      run: echo stepify-tail-check-mod-tidy
    - name: stepify-probe-check-lint
      run: echo stepify-probe-check-lint
    - uses: golangci/golangci-lint-action@82d40c283aeb1f2b6595839195e95c2d6a49081b
      with:
        version: v1.54.2
        only-new-issues: true
    - name: stepify-tail-check-lint
      run: echo stepify-tail-check-lint
    - name: stepify-probe-check-fmt
      run: echo stepify-probe-check-fmt
    - name: stepify-fault-check-fmt
      run: exit 1
    - run: 'go fmt ./...

        echo "==> Checking that code complies with go fmt requirements..."

        git diff --exit-code; if [ $$? -eq 1 ]; then \

        echo "Found files that are not fmt''ed."; \

        echo "You can use the command: \`go fmt ./...\` to reformat code."; \

        exit 1; \

        fi

        '
    - name: stepify-tail-check-fmt
      run: echo stepify-tail-check-fmt
    - name: stepify-probe-check-generate
      run: echo stepify-probe-check-generate
    - run: "export PATH=$PATH:$(go env GOPATH)/bin\nmake generate\nuncommitted=\"$(git status -s)\"\n\
        if [[ -z \"$uncommitted\" ]]; then\n  echo \"OK\"\nelse\n  echo \"Docs have been updated, but\
        \ the compiled docs have not been committed.\"\n  echo \"Run 'make generate', and commit the result\
        \ to resolve this error.\"\n  echo \"Generated but uncommitted files:\"\n  echo \"$uncommitted\"\
        \n  exit 1\nfi\n"
    - name: stepify-tail-check-generate
      run: echo stepify-tail-check-generate
